// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// matrix_reduce
NumericVector matrix_reduce(NumericMatrix m, IntegerVector idx, IntegerVector factors, std::string method);
RcppExport SEXP prtools_matrix_reduce(SEXP mSEXP, SEXP idxSEXP, SEXP factorsSEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type m(mSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type idx(idxSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type factors(factorsSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    __result = Rcpp::wrap(matrix_reduce(m, idx, factors, method));
    return __result;
END_RCPP
}
