// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// matrix_reduce
NumericVector matrix_reduce(NumericMatrix m, IntegerVector idx, IntegerVector factors, std::string method);
RcppExport SEXP prtools_matrix_reduce(SEXP mSEXP, SEXP idxSEXP, SEXP factorsSEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type m(mSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type idx(idxSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type factors(factorsSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    rcpp_result_gen = Rcpp::wrap(matrix_reduce(m, idx, factors, method));
    return rcpp_result_gen;
END_RCPP
}
