# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

matrix_reduce <- function(m, idx, factors, method) {
    .Call('prtools_matrix_reduce', PACKAGE = 'prtools', m, idx, factors, method)
}

