context("ExpressionSet functions")

test_that("reducing works", {
    m <- matrix(c(1,1,1,2,2,2,1,1,1,3,3,3), ncol=3, byrow=TRUE)
    rownames(m) <- paste0("f", 1:4)
    eset <- ExpressionSet(m)
    gr <- c(1,1,2,2)
    red <- eset_reduce(eset, rownames(m), gr)
    expect_equal(c(2,3), dim(exprs(red)))
    red <- eset_reduce(eset, rownames(m), gr, method="median")
    expect_equal(c(2,3), dim(exprs(red)))
    red <- eset_reduce(eset, rownames(m), gr, method="max")
    expect_equal(c(2,3), dim(exprs(red)))
    red <- eset_reduce(eset, rownames(m), c(1,1,1,2), method="median")
    expect_equal(c(2,3), dim(exprs(red)))
})
